// Backend integration point: replace with API calls to /api/reports

export type ReportCategory =
  | 'financial-statements' |'management' |'tax' |'ar-ap' |'budget' |'audit' |'custom';

// [BARU] 'Word' ditambahkan karena CALK asli (lihat downloadCalk() di
// agent-ai/lib/api.js) bisa diunduh sebagai .docx, bukan cuma PDF/Excel/CSV.
export type ReportFormat = 'PDF' | 'Excel' | 'CSV' | 'Word';
export type ReportStatus = 'ready' | 'generating' | 'scheduled' | 'error';

export interface Report {
  id: string;
  name: string;
  description: string;
  category: ReportCategory;
  period: string;
  lastGenerated: string;
  createdBy: string;
  formats: ReportFormat[];
  status: ReportStatus;
  size?: string;
  tags?: string[];
}

export interface ScheduledReport {
  id: string;
  reportName: string;
  frequency: 'Daily' | 'Weekly' | 'Monthly' | 'Quarterly' | 'Yearly';
  recipients: string[];
  nextRun: string;
  status: 'Active' | 'Paused' | 'Error';
  format: ReportFormat;
}

export const reportCategories = [
  { id: 'all', label: 'All Reports', icon: 'LayoutGrid', count: 24 },
  { id: 'financial-statements', label: 'Financial Statements', icon: 'FileBarChart', count: 6 },
  { id: 'management', label: 'Management Reports', icon: 'TrendingUp', count: 4 },
  { id: 'tax', label: 'Tax Reports', icon: 'Receipt', count: 3 },
  { id: 'ar-ap', label: 'AR/AP Reports', icon: 'ArrowLeftRight', count: 4 },
  { id: 'budget', label: 'Budget Reports', icon: 'Target', count: 3 },
  { id: 'audit', label: 'Audit Reports', icon: 'ShieldCheck', count: 2 },
  { id: 'custom', label: 'Custom Reports', icon: 'Sliders', count: 2 },
];

export const reports: Report[] = [
  {
    id: 'rpt-001',
    name: 'Profit & Loss Statement',
    description: 'Comprehensive income statement showing revenue, expenses, and net profit for the selected period.',
    category: 'financial-statements',
    period: 'Jan – Aug 2026',
    lastGenerated: '28 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '284 KB',
    tags: ['Core', 'Monthly'],
  },
  {
    id: 'rpt-002',
    name: 'Balance Sheet',
    description: 'Statement of financial position showing assets, liabilities, and equity at period end.',
    category: 'financial-statements',
    period: 'Aug 2026',
    lastGenerated: '28 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '196 KB',
    tags: ['Core', 'Monthly'],
  },
  {
    id: 'rpt-003',
    name: 'Cash Flow Statement',
    description: 'Operating, investing, and financing cash flows with reconciliation to opening balance.',
    category: 'financial-statements',
    period: 'Jan – Aug 2026',
    lastGenerated: '27 Aug 2026',
    createdBy: 'Budi Santoso',
    formats: ['PDF', 'Excel', 'CSV'],
    status: 'ready',
    size: '312 KB',
    tags: ['Core'],
  },
  {
    id: 'rpt-004',
    name: 'Trial Balance',
    description: 'Complete listing of all general ledger accounts with debit and credit balances.',
    category: 'financial-statements',
    period: 'Aug 2026',
    lastGenerated: '28 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel', 'CSV'],
    status: 'ready',
    size: '428 KB',
    tags: ['Core'],
  },
  {
    id: 'rpt-005',
    name: 'General Ledger',
    description: 'Detailed transaction listing for all accounts with running balances.',
    category: 'financial-statements',
    period: 'Aug 2026',
    lastGenerated: '26 Aug 2026',
    createdBy: 'Agus Prasetyo',
    formats: ['PDF', 'Excel', 'CSV'],
    status: 'ready',
    size: '1.2 MB',
    tags: ['Detailed'],
  },
  {
    id: 'rpt-006',
    name: 'Statement of Changes in Equity',
    description: 'Movement in equity components including retained earnings, share capital, and reserves.',
    category: 'financial-statements',
    period: 'Jan – Aug 2026',
    lastGenerated: '25 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '168 KB',
    tags: ['Core'],
  },
  {
    id: 'rpt-007',
    name: 'Executive Dashboard Report',
    description: 'High-level KPI summary with trend analysis for management review.',
    category: 'management',
    period: 'Jan – Aug 2026',
    lastGenerated: '28 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF'],
    status: 'ready',
    size: '892 KB',
    tags: ['Management', 'Weekly'],
  },
  {
    id: 'rpt-008',
    name: 'Financial Ratios Analysis',
    description: 'Liquidity, profitability, solvency, and efficiency ratios with industry benchmarks.',
    category: 'management',
    period: 'Jan – Aug 2026',
    lastGenerated: '27 Aug 2026',
    createdBy: 'Budi Santoso',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '344 KB',
    tags: ['Management', 'Analytics'],
  },
  {
    id: 'rpt-009',
    name: 'Cost Analysis Report',
    description: 'Breakdown of operating costs by department, category, and cost center.',
    category: 'management',
    period: 'Jan – Aug 2026',
    lastGenerated: '24 Aug 2026',
    createdBy: 'Agus Prasetyo',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '512 KB',
    tags: ['Management'],
  },
  {
    id: 'rpt-010',
    name: 'Revenue Analysis Report',
    description: 'Revenue breakdown by product line, customer segment, and sales channel.',
    category: 'management',
    period: 'Jan – Aug 2026',
    lastGenerated: '23 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '476 KB',
    tags: ['Management', 'Revenue'],
  },
  {
    id: 'rpt-011',
    name: 'Monthly Tax Report (PPh 21)',
    description: 'Employee income tax withholding summary with individual and aggregate amounts.',
    category: 'tax',
    period: 'Aug 2026',
    lastGenerated: '20 Aug 2026',
    createdBy: 'Agus Prasetyo',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '284 KB',
    tags: ['Tax', 'Monthly'],
  },
  {
    id: 'rpt-012',
    name: 'VAT Report (PPN)',
    description: 'Value added tax input/output reconciliation for the reporting period.',
    category: 'tax',
    period: 'Aug 2026',
    lastGenerated: '20 Aug 2026',
    createdBy: 'Agus Prasetyo',
    formats: ['PDF', 'Excel', 'CSV'],
    status: 'ready',
    size: '196 KB',
    tags: ['Tax', 'Monthly'],
  },
  {
    id: 'rpt-013',
    name: 'Annual Tax Report (PPh Badan)',
    description: 'Corporate income tax return with supporting schedules and reconciliation.',
    category: 'tax',
    period: 'FY 2025',
    lastGenerated: '15 Apr 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '1.8 MB',
    tags: ['Tax', 'Annual'],
  },
  {
    id: 'rpt-014',
    name: 'AR Aging Report',
    description: 'Accounts receivable aging analysis by customer with overdue classification.',
    category: 'ar-ap',
    period: 'Aug 2026',
    lastGenerated: '28 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel', 'CSV'],
    status: 'ready',
    size: '368 KB',
    tags: ['AR', 'Weekly'],
  },
  {
    id: 'rpt-015',
    name: 'AP Aging Report',
    description: 'Accounts payable aging analysis by vendor with upcoming payment schedule.',
    category: 'ar-ap',
    period: 'Aug 2026',
    lastGenerated: '28 Aug 2026',
    createdBy: 'Budi Santoso',
    formats: ['PDF', 'Excel', 'CSV'],
    status: 'ready',
    size: '312 KB',
    tags: ['AP', 'Weekly'],
  },
  {
    id: 'rpt-016',
    name: 'Customer Statement',
    description: 'Individual customer account statement with transaction history and balance.',
    category: 'ar-ap',
    period: 'Aug 2026',
    lastGenerated: '26 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF'],
    status: 'ready',
    size: '148 KB',
    tags: ['AR'],
  },
  {
    id: 'rpt-017',
    name: 'Vendor Statement',
    description: 'Individual vendor account statement with purchase history and outstanding balance.',
    category: 'ar-ap',
    period: 'Aug 2026',
    lastGenerated: '25 Aug 2026',
    createdBy: 'Budi Santoso',
    formats: ['PDF'],
    status: 'ready',
    size: '132 KB',
    tags: ['AP'],
  },
  {
    id: 'rpt-018',
    name: 'Budget vs Actual',
    description: 'Variance analysis comparing budgeted figures to actual results with explanations.',
    category: 'budget',
    period: 'Jan – Aug 2026',
    lastGenerated: '27 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '428 KB',
    tags: ['Budget', 'Monthly'],
  },
  {
    id: 'rpt-019',
    name: 'Forecast Report',
    description: 'Rolling 12-month financial forecast with scenario analysis.',
    category: 'budget',
    period: 'Sep 2026 – Aug 2027',
    lastGenerated: '25 Aug 2026',
    createdBy: 'Budi Santoso',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '516 KB',
    tags: ['Budget', 'Forecast'],
  },
  {
    id: 'rpt-020',
    name: 'Department Budget Report',
    description: 'Budget allocation and utilization by department with headcount costs.',
    category: 'budget',
    period: 'Jan – Aug 2026',
    lastGenerated: '23 Aug 2026',
    createdBy: 'Agus Prasetyo',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '384 KB',
    tags: ['Budget'],
  },
  {
    id: 'rpt-021',
    name: 'Audit Report FY 2025',
    description: 'Final audit report with findings, management responses, and recommendations.',
    category: 'audit',
    period: 'FY 2025',
    lastGenerated: '15 Mar 2026',
    createdBy: 'Rina Kusuma',
    formats: ['PDF'],
    status: 'ready',
    size: '2.4 MB',
    tags: ['Audit', 'Annual'],
  },
  {
    id: 'rpt-022',
    name: 'Internal Audit Progress Report',
    description: 'Current audit cycle progress with findings summary and completion metrics.',
    category: 'audit',
    period: 'FY 2026',
    lastGenerated: '20 Aug 2026',
    createdBy: 'Rina Kusuma',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '684 KB',
    tags: ['Audit'],
  },
  {
    id: 'rpt-023',
    name: 'Profitability by Product Line',
    description: 'Custom profitability analysis segmented by product line with margin waterfall.',
    category: 'custom',
    period: 'Jan – Aug 2026',
    lastGenerated: '22 Aug 2026',
    createdBy: 'Sari Dewi',
    formats: ['PDF', 'Excel'],
    status: 'ready',
    size: '592 KB',
    tags: ['Custom', 'Revenue'],
  },
  {
    id: 'rpt-024',
    name: 'Cash Flow Forecast (13-Week)',
    description: 'Short-term rolling cash flow forecast by week for liquidity management.',
    category: 'custom',
    period: 'Sep – Nov 2026',
    lastGenerated: '26 Aug 2026',
    createdBy: 'Budi Santoso',
    formats: ['Excel', 'CSV'],
    status: 'ready',
    size: '248 KB',
    tags: ['Custom', 'Forecast'],
  },
];

export const scheduledReports: ScheduledReport[] = [
  {
    id: 'sched-001',
    reportName: 'Executive Dashboard Report',
    frequency: 'Weekly',
    recipients: ['cfo@nusantara.co.id', 'finance@nusantara.co.id'],
    nextRun: '01 Sep 2026',
    status: 'Active',
    format: 'PDF',
  },
  {
    id: 'sched-002',
    reportName: 'AR Aging Report',
    frequency: 'Weekly',
    recipients: ['ar@nusantara.co.id', 'sari.dewi@nusantara.co.id'],
    nextRun: '01 Sep 2026',
    status: 'Active',
    format: 'Excel',
  },
  {
    id: 'sched-003',
    reportName: 'Profit & Loss Statement',
    frequency: 'Monthly',
    recipients: ['board@nusantara.co.id', 'cfo@nusantara.co.id'],
    nextRun: '01 Sep 2026',
    status: 'Active',
    format: 'PDF',
  },
  {
    id: 'sched-004',
    reportName: 'Monthly Tax Report (PPh 21)',
    frequency: 'Monthly',
    recipients: ['tax@nusantara.co.id', 'agus.p@nusantara.co.id'],
    nextRun: '20 Sep 2026',
    status: 'Active',
    format: 'PDF',
  },
  {
    id: 'sched-005',
    reportName: 'Budget vs Actual',
    frequency: 'Monthly',
    recipients: ['cfo@nusantara.co.id', 'dept.heads@nusantara.co.id'],
    nextRun: '05 Sep 2026',
    status: 'Active',
    format: 'Excel',
  },
  {
    id: 'sched-006',
    reportName: 'Cash Flow Statement',
    frequency: 'Monthly',
    recipients: ['treasury@nusantara.co.id'],
    nextRun: '01 Sep 2026',
    status: 'Paused',
    format: 'PDF',
  },
  {
    id: 'sched-007',
    reportName: 'Annual Tax Report (PPh Badan)',
    frequency: 'Yearly',
    recipients: ['tax@nusantara.co.id', 'cfo@nusantara.co.id'],
    nextRun: '31 Mar 2027',
    status: 'Active',
    format: 'PDF',
  },
];

export const reportPreviewData = {
  profitLoss: {
    revenue: [
      { label: 'Product Sales', amount: 6840000000 },
      { label: 'Service Revenue', amount: 1280000000 },
      { label: 'Other Income', amount: 300000000 },
    ],
    totalRevenue: 8420000000,
    cogs: 4700000000,
    grossProfit: 3720000000,
    operatingExpenses: [
      { label: 'Salaries & Benefits', amount: 980000000 },
      { label: 'Marketing & Sales', amount: 420000000 },
      { label: 'General & Administrative', amount: 280000000 },
      { label: 'Depreciation', amount: 180000000 },
      { label: 'Other Operating', amount: 40000000 },
    ],
    totalOpex: 1900000000,
    ebit: 1820000000,
    interestExpense: -18000000,
    taxExpense: -38000000,
    netProfit: 1840000000,
  },
};