-- seed_coa_npi.sql
-- =============================================================
-- Master COA klien NPI -> tabel management_client_coa (156 akun).
-- DIHASILKAN OTOMATIS oleh migrations/generate_seed_coa.py dari
-- dataset/COA/COA_Clients_GOUF.xlsx sheet "COA NPI" -- JANGAN diedit
-- manual, ubah Excel-nya lalu generate ulang.
--
-- normal_balance diturunkan dari ACCOUNT CLASSIFICATION (+ akun kontra),
-- lihat generate_seed_coa.py::normal_balance().
--
-- KLIEN: dicari lewat nama_client IN ('NPI', 'PT NUSA PENIDA INVESTMENTS'), GAGAL dengan pesan
-- jelas kalau belum ada. client_id/client_code TIDAK di-hardcode.
--
-- PRASYARAT: venv\Scripts\python migrations\16-create_management_client_coa.py
--
-- Cara pakai:
--   cd backend
--   venv\Scripts\python migrations\run_seed.py seed_coa_npi.sql
--
-- Idempotensi: ON CONFLICT (client_id, acc_no) DO UPDATE -- aman dijalankan
-- ulang; isi akun ditimpa dari Excel, akun yang di-soft-delete tetap terhapus.

DO $do$
DECLARE
    v_client_id   UUID;
    v_client_code VARCHAR(50);
BEGIN
    SELECT id, client_code INTO v_client_id, v_client_code
    FROM management_clients
    WHERE deleted_at IS NULL
      AND upper(trim(nama_client)) IN ('NPI', 'PT NUSA PENIDA INVESTMENTS')
    ORDER BY created_at
    LIMIT 1;

    IF v_client_id IS NULL THEN
        RAISE EXCEPTION 'Klien NPI belum ada di management_clients (dicari nama_client IN (''NPI'', ''PT NUSA PENIDA INVESTMENTS'')). Buat dulu lewat halaman Clients, lalu jalankan ulang seed ini.';
    END IF;

    INSERT INTO management_client_coa (
        client_id, client_code, acc_no, account_name, account_classification, account_head, account_sub, description, international_standard_group, standard_account_code, ifrs_taxonomy_reference, ifrs_source, normal_balance
    )
    SELECT v_client_id, v_client_code, v.*
    FROM (VALUES
        ('1-1100', 'Cash on hand (store)', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1104', 'BANK MANDIRI #265', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1103', 'Mandiri Resto #9273', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1102', 'OCBC IDR #7094', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1106', 'Mandiri Shop #5108', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1107', 'Mandiri Deli #5058', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1101', 'Petty cash', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Petty cash and cash on hand used for daily operational transactions.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_petty', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1109', 'Mandiri Deli Grocery (482)', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1111', 'Cash on hand (deli)', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-1108', 'OCBC EURO #7094', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-2004', 'Account Receivable - Related Party', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-2001', 'Accounts Receivable', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-303', 'Cash on hand', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-304', 'EDC BCA', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-305', 'EDC MANDIRI 9273', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-4001', 'Kitchen utensils', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-2003', 'Prepayments', 'ASSET', 'CURRENT ASSET', 'PREPAYMENTS', 'Costs paid in advance and recognized as assets until consumed.', 'Assets > Current assets > Prepayments and other current assets', 'std_asset_current_prepayment', 'Prepayments and other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-2002', 'Shareholder Receivable', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-2005', 'Employee Advances', 'ASSET', 'CURRENT ASSET', 'ADVANCES', 'Advances and down payments recoverable through goods, services, or settlement.', 'Assets > Current assets > Other current assets', 'std_asset_current_advance', 'Other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-3000', 'Inventory', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-3002', 'Inventory-Beverege', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-3001', 'Inventory-Food', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-3003', 'Inventory - store', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('13004', 'Inventory-Food_Deli', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('13005', 'Inventory-Beverage_Deli', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('13006', 'Inventory-Other_Deli', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-307', 'Prepaid Rent', 'ASSET', 'CURRENT ASSET', 'PREPAYMENTS', 'Costs paid in advance and recognized as assets until consumed.', 'Assets > Current assets > Prepayments and other current assets', 'std_asset_current_prepayment', 'Prepayments and other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-306', 'QRIS MANDIRI', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-308', 'VAT IN', 'ASSET', 'CURRENT ASSET', 'INDIRECT TAX RECEIVABLE', 'Recoverable input VAT or other indirect tax receivable.', 'Assets > Current assets > Current tax and other receivables', 'std_asset_current_tax_vat_receivable', 'Current tax assets / other receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('3000-3', 'Inventory assets', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('712', 'Accumulated Depreciation on Bar equipment', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('713', 'Accumulated Depreciation on Furniture and Fittings', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('714', 'Accumulated Depreciation on Kitchen equipment', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('711', 'Accumulated Depreciation on Office Equipment', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('716', 'Accumulated Depreciation on Tableware', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('717', 'Accumulated Depreciation on Electrical Equipment', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('719', 'Accumulated Depreciation on Rental equipment', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('718', 'Accumulated Depreciation on Fixed Assets – Leasehold Improvements', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('715', 'Accumulated Depreciation on Land', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('721', 'Accumulated Depreciation on Computer Equipment', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-5003', 'Bar equipment', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5001', 'Furniture and Fittings', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5006', 'Inventory Linen', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5002', 'Kitchen equipment', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5007', 'Land', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Land held for operational use.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_land', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5004', 'Office Equipment', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('722', 'Provision on Breakage & Loss (Linen)', 'ASSET', 'NON-CURRENT ASSET', 'ASSET IMPAIRMENT / ALLOWANCE', 'Contra-asset allowance or provision against operational non-current assets, excluding accumulated depreciation.', 'Assets > Non-current assets > Property, plant and equipment / other non-current assets', 'std_asset_noncurrent_impairment_allowance', 'Property, plant and equipment / impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('723', 'Electrical Equipment', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('724', 'Rental equipment', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('725', 'Accumulated Depreciation on Store Equipment & Fixtures', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('726', 'Accumulated Depreciation on Fixed Asset-Leasehold Improvement', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-6004', 'Tableware', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5005', 'Computer Equipment', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5009', 'Small equipment', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5008', 'Fixed Assets – Leasehold Improvements', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Buildings and building improvements used in operations.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_building', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-5000', 'Store Equipment & Fixtures', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-6001', 'Construction in progress', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Construction in progress or assets under construction.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_cip', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('2-1003', 'Account Payable - Related Party', 'LIABILITY', 'CURRENT LIABILITY', 'TRADE PAYABLES', 'Amounts payable to suppliers for goods and services received in the ordinary course of business.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_trade', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-1001', 'Accounts Payable', 'LIABILITY', 'CURRENT LIABILITY', 'TRADE PAYABLES', 'Amounts payable to suppliers for goods and services received in the ordinary course of business.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_trade', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-1006', 'Account Payable', 'LIABILITY', 'CURRENT LIABILITY', 'TRADE PAYABLES', 'Amounts payable to suppliers for goods and services received in the ordinary course of business.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_trade', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-100x', 'Accounts Payable-Jose', 'LIABILITY', 'CURRENT LIABILITY', 'TRADE PAYABLES', 'Amounts payable to suppliers for goods and services received in the ordinary course of business.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_trade', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2003', 'Income Tax Payable', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-1105', 'Jose Personal Funds', 'ASSET', 'CURRENT ASSET', 'RELATED PARTY RECEIVABLES', 'Amounts receivable from shareholders, directors, affiliates, or other related parties.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_related_party', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('2-1005', 'PB 1 Payable', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Other taxes and local levies payable, including sales/service taxes where applicable.', 'Liabilities > Current liabilities > Tax liabilities', 'std_liability_current_tax_other_payable', 'Current tax liabilities / other payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2001', 'Sales Tax', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Other taxes and local levies payable, including sales/service taxes where applicable.', 'Liabilities > Current liabilities > Tax liabilities', 'std_liability_current_tax_other_payable', 'Current tax liabilities / other payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-1004', 'Service Charge Payable', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER PAYABLES', 'Other short-term payables and unsettled liabilities.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_other', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2002', 'Employee Tax Payable PPH 21', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2004', 'Accrued BPJS Kesehatan', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Expenses incurred but not yet invoiced or paid.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_expense', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2005', 'Accrued BPJS Ketenagakerjaan', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Expenses incurred but not yet invoiced or paid.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_expense', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2006', 'Tax Payable Art 4(2)', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2007', 'Tax Payable Art.23', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2009', 'VAT OUT', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Output VAT or other indirect taxes payable.', 'Liabilities > Current liabilities > Tax liabilities', 'std_liability_current_tax_vat_payable', 'Current tax liabilities / other payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-1002', 'Wages Payable', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Accrued payroll, salaries, bonuses, social security, and employee-related expenses.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_employee', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-2008', 'Customer Deposit', 'LIABILITY', 'CURRENT LIABILITY', 'CONTRACT / DEFERRED REVENUE', 'Customer deposits, advances, or revenue received before the related performance obligation is satisfied.', 'Liabilities > Current liabilities > Contract liabilities and other payables', 'std_liability_current_deferred_revenue', 'Contract liabilities / other current liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('826', 'Superannuation Payable', 'LIABILITY', 'NON-CURRENT LIABILITY', 'EMPLOYEE BENEFIT OBLIGATIONS', 'Long-term employee benefit or post-employment benefit obligations.', 'Liabilities > Non-current liabilities > Employee benefit obligations', 'std_liability_noncurrent_employee_benefit', 'Employee benefit obligations', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('850', 'Suspense', 'ASSET', 'CURRENT ASSET', 'OTHER CURRENT ASSETS', 'Other current assets not separately classified.', 'Assets > Current assets > Other current assets', 'std_asset_current_other', 'Other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('880', 'Owner A Drawings', 'EQUITY', 'EQUITY', 'OWNER DRAWINGS', 'Owner drawings or distributions recorded directly in equity.', 'Equity > Other equity', 'std_equity_owner_drawing', 'Other equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('881', 'Owner A Funds Introduced', 'EQUITY', 'EQUITY', 'ADDITIONAL PAID-IN CAPITAL', 'Additional paid-in capital, share premium, or similar contributed equity.', 'Equity > Other contributed equity', 'std_equity_additional_paid_in_capital', 'Share premium / other contributed equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-3002', 'Loan to Jose', 'LIABILITY', 'CURRENT LIABILITY', 'BORROWINGS', 'Short-term loans, overdrafts, and current portions of borrowings.', 'Liabilities > Current liabilities > Borrowings', 'std_liability_current_borrowing', 'Current borrowings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-3001', 'Loan', 'LIABILITY', 'CURRENT LIABILITY', 'BORROWINGS', 'Short-term loans, overdrafts, and current portions of borrowings.', 'Liabilities > Current liabilities > Borrowings', 'std_liability_current_borrowing', 'Current borrowings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-1000', 'Current Year Earnings', 'EQUITY', 'EQUITY', 'CURRENT PERIOD EARNINGS', 'Current period profit or loss carried within equity before closing.', 'Equity > Retained earnings / current period result', 'std_equity_current_period_earnings', 'Retained earnings / profit or loss', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-1001', 'Share Capital', 'EQUITY', 'EQUITY', 'SHARE CAPITAL', 'Issued and paid-in share capital or owners'' capital.', 'Equity > Share capital', 'std_equity_share_capital', 'Issued capital', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-1002', 'Retained Earnings', 'EQUITY', 'EQUITY', 'RETAINED EARNINGS', 'Accumulated retained earnings or accumulated losses from prior periods.', 'Equity > Retained earnings', 'std_equity_retained_earnings', 'Retained earnings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-1007', 'Discount given', 'REVENUE', 'OPERATING REVENUE', 'SALES DEDUCTIONS', 'Sales discounts or rebates presented as a reduction of revenue.', 'Income > Revenue deductions', 'std_revenue_operating_discount', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-1001', 'Interest Income', 'OTHER INCOME', 'NON-OPERATING INCOME', 'INTEREST INCOME', 'Interest income from bank balances, deposits, and other financial assets.', 'Income > Finance income / other income', 'std_other_income_interest', 'Finance income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-1008', 'Other Revenue', 'REVENUE', 'OPERATING REVENUE', 'OTHER OPERATING REVENUE', 'Other revenue generated from ordinary operating activities.', 'Income > Revenue', 'std_revenue_operating_other', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-1005', 'Sales beverage', 'REVENUE', 'OPERATING REVENUE', 'FOOD & BEVERAGE REVENUE', 'Restaurant, café, food, and beverage revenue.', 'Income > Revenue', 'std_revenue_operating_food_beverage', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-1004', 'Sales food', 'REVENUE', 'OPERATING REVENUE', 'FOOD & BEVERAGE REVENUE', 'Restaurant, café, food, and beverage revenue.', 'Income > Revenue', 'std_revenue_operating_food_beverage', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-0001', 'Sales - card (EDC)', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-0000', 'Sales - cash', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-0002', 'Sales - QRIS', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-0100', 'Deli Sales - cash', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-0110', 'Deli Sales - card', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-0111', 'Deli sales - Transfer', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-0120', 'Deli Sales - QRIS', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-1006', 'Complimentary', 'REVENUE', 'OPERATING REVENUE', 'OTHER OPERATING REVENUE', 'Other revenue generated from ordinary operating activities.', 'Income > Revenue', 'std_revenue_operating_other', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('5-1002', 'Cost of Sales Beverage', 'COST OF SALES', 'COST OF REVENUE', 'BEVERAGE COST', 'Direct beverage cost associated with revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_beverage', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('5-1003', 'Cost of Sales Deli Shop', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('5-1001', 'Cost of Sales Food', 'COST OF SALES', 'COST OF REVENUE', 'DIRECT MATERIAL / FOOD COST', 'Direct cost of materials, food, ingredients, or goods consumed in producing revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_direct_material', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-2001', 'Advertising, Marketing & Commission', 'EXPENSE', 'OPERATING EXPENSE', 'MARKETING & PROMOTION', 'Advertising, promotion, marketing, sales commission, and partnership costs.', 'Expenses > Operating expenses', 'std_expense_operating_marketing', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3006', 'Bank charges', 'EXPENSE', 'OPERATING EXPENSE', 'BANK & PAYMENT CHARGES', 'Bank administration, merchant discount rate, card charges, transfer charges, and payment processing fees.', 'Expenses > Operating expenses / finance costs', 'std_expense_operating_bank_payment_charges', 'Other operating expenses / finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1002', 'Cleaning', 'EXPENSE', 'OPERATING EXPENSE', 'CLEANING & SECURITY', 'Cleaning, security, waste removal, and related facility-support costs.', 'Expenses > Operating expenses', 'std_expense_operating_cleaning_security', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3022', 'Cleaning supplies', 'EXPENSE', 'OPERATING EXPENSE', 'CLEANING & SECURITY', 'Cleaning, security, waste removal, and related facility-support costs.', 'Expenses > Operating expenses', 'std_expense_operating_cleaning_security', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3009', 'Consulting & Accounting', 'EXPENSE', 'OPERATING EXPENSE', 'PROFESSIONAL FEES', 'Legal, audit, accounting, consulting, and other professional service fees.', 'Expenses > Operating expenses', 'std_expense_operating_professional_fees', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3016', 'Decoration', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1003', 'Depreciation Expense', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3019', 'Donation', 'EXPENSE', 'OPERATING EXPENSE', 'DONATION & COMMUNITY', 'Donations and community-related expenditure.', 'Expenses > Other operating expenses', 'std_expense_operating_donation', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3002', 'Electricity, water & utilities', 'EXPENSE', 'OPERATING EXPENSE', 'UTILITIES', 'Electricity, water, gas, power, and other utility costs.', 'Expenses > Operating expenses', 'std_expense_operating_utilities', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3013', 'Entertainment', 'EXPENSE', 'OPERATING EXPENSE', 'MEALS & ENTERTAINMENT', 'Meals, entertainment, hospitality, and employee refreshments.', 'Expenses > Operating expenses', 'std_expense_operating_meals_entertainment', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('9-1002', 'Interest Tax Expense', 'OTHER EXPENSE', 'FINANCE COST', 'INTEREST EXPENSE', 'Interest and borrowing costs recognized in profit or loss.', 'Expenses > Finance costs', 'std_other_expense_interest', 'Finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3012', 'Office Expenses', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3020', 'Other expense', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3026', 'Outsourcing BPJS', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3024', 'Outsourcing Fee', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3025', 'Outsourcing Salary', 'EXPENSE', 'OPERATING EXPENSE', 'SALARIES & WAGES', 'Salaries, wages, payroll, and regular employee compensation.', 'Expenses > Employee benefits expense', 'std_expense_operating_salary_wages', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3004', 'Phone & Internet', 'EXPENSE', 'OPERATING EXPENSE', 'COMMUNICATION & INTERNET', 'Telephone, internet, communication, and connectivity costs.', 'Expenses > Operating expenses', 'std_expense_operating_communication', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3005', 'Printing & Stationery', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1013', 'Professional Service', 'EXPENSE', 'OPERATING EXPENSE', 'PROFESSIONAL FEES', 'Legal, audit, accounting, consulting, and other professional service fees.', 'Expenses > Operating expenses', 'std_expense_operating_professional_fees', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1008', 'Rent', 'EXPENSE', 'OPERATING EXPENSE', 'RENT EXPENSE', 'Rent and operating lease expenses not capitalized under applicable accounting requirements.', 'Expenses > Operating expenses', 'std_expense_operating_rent', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3017', 'Rent expense', 'EXPENSE', 'OPERATING EXPENSE', 'RENT EXPENSE', 'Rent and operating lease expenses not capitalized under applicable accounting requirements.', 'Expenses > Operating expenses', 'std_expense_operating_rent', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1001', 'Repairs and Maintenance', 'EXPENSE', 'OPERATING EXPENSE', 'REPAIR & MAINTENANCE', 'Repair, maintenance, and upkeep of buildings, vehicles, equipment, and facilities.', 'Expenses > Operating expenses', 'std_expense_operating_repair_maintenance', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3014', 'Small equipment', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3023', 'Software Licenses', 'EXPENSE', 'OPERATING EXPENSE', 'TAXES & LICENSES', 'Non-income taxes, licenses, permits, and levies expensed in operations.', 'Expenses > Operating expenses', 'std_expense_operating_tax_license', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3018', 'Subscription fee', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1010', 'Subscriptions', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3110', 'Gas_tank', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3111', 'Supplies', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-31101', 'Gas', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3027', 'Tax Expense', 'EXPENSE', 'OPERATING EXPENSE', 'TAXES & LICENSES', 'Non-income taxes, licenses, permits, and levies expensed in operations.', 'Expenses > Operating expenses', 'std_expense_operating_tax_license', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3003', 'Transport cost', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-2002', 'Travel expense', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1009', 'Wages and Salaries', 'EXPENSE', 'OPERATING EXPENSE', 'SALARIES & WAGES', 'Salaries, wages, payroll, and regular employee compensation.', 'Expenses > Employee benefits expense', 'std_expense_operating_salary_wages', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3115', 'Kitchen utensils', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3114', 'Kitchen utensils_exp', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('478', 'Superannuation', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1000', 'General Expenses', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1004', 'Freight & Courier', 'EXPENSE', 'OPERATING EXPENSE', 'FREIGHT & COURIER', 'Courier, expedition, shipping, and delivery costs not classified as cost of sales.', 'Expenses > Operating expenses', 'std_expense_operating_freight_courier', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1005', 'Insurance', 'EXPENSE', 'OPERATING EXPENSE', 'INSURANCE', 'Insurance premiums and related insurance expense.', 'Expenses > Operating expenses', 'std_expense_operating_insurance', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1006', 'Light, Power, Heating', 'EXPENSE', 'OPERATING EXPENSE', 'UTILITIES', 'Electricity, water, gas, power, and other utility costs.', 'Expenses > Operating expenses', 'std_expense_operating_utilities', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1007', 'Motor Vehicle Expenses', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1011', 'Travel - National', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-1012', 'Travel - International', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3007', 'Credit/debit card charges', 'EXPENSE', 'OPERATING EXPENSE', 'BANK & PAYMENT CHARGES', 'Bank administration, merchant discount rate, card charges, transfer charges, and payment processing fees.', 'Expenses > Operating expenses / finance costs', 'std_expense_operating_bank_payment_charges', 'Other operating expenses / finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3008', 'Legal expenses', 'EXPENSE', 'OPERATING EXPENSE', 'PROFESSIONAL FEES', 'Legal, audit, accounting, consulting, and other professional service fees.', 'Expenses > Operating expenses', 'std_expense_operating_professional_fees', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3010', 'Income Tax Expense', 'INCOME TAX', 'INCOME TAX EXPENSE', 'INCOME TAX EXPENSE', 'Current and deferred income tax expense recognized in profit or loss.', 'Expenses > Income tax expense', 'std_income_tax_expense', 'Income tax expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3015', 'Complimentary expense', 'EXPENSE', 'OPERATING EXPENSE', 'MEALS & ENTERTAINMENT', 'Meals, entertainment, hospitality, and employee refreshments.', 'Expenses > Operating expenses', 'std_expense_operating_meals_entertainment', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3028', 'BPJS Kesehatan Expense', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3029', 'BPJS Ketenagakerjaan Expense', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3030', 'CONSULTING SERVICE FEE', 'EXPENSE', 'OPERATING EXPENSE', 'PROFESSIONAL FEES', 'Legal, audit, accounting, consulting, and other professional service fees.', 'Expenses > Operating expenses', 'std_expense_operating_professional_fees', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3031', 'Penalty Expense', 'EXPENSE', 'OPERATING EXPENSE', 'PENALTIES & FINES', 'Penalties, fines, and similar non-routine operating charges.', 'Expenses > Other expenses', 'std_expense_operating_penalty', 'Other expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3011', 'Trash Removal', 'EXPENSE', 'OPERATING EXPENSE', 'CLEANING & SECURITY', 'Cleaning, security, waste removal, and related facility-support costs.', 'Expenses > Operating expenses', 'std_expense_operating_cleaning_security', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('801', 'Unpaid Expense Claims', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Expenses incurred but not yet invoiced or paid.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_expense', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('860', 'Rounding', 'OTHER EXPENSE', 'NON-OPERATING EXPENSE', 'OTHER EXPENSE', 'Other non-operating expense not separately classified.', 'Expenses > Other expenses', 'std_other_expense_misc', 'Other expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('877', 'Tracking Transfers', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash or bank funds in transit or temporary clearing pending settlement.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_transit', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-3112', 'Entertainment supplies', 'EXPENSE', 'OPERATING EXPENSE', 'MEALS & ENTERTAINMENT', 'Meals, entertainment, hospitality, and employee refreshments.', 'Expenses > Operating expenses', 'std_expense_operating_meals_entertainment', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('9-1001', 'Interest Expense', 'OTHER EXPENSE', 'FINANCE COST', 'INTEREST EXPENSE', 'Interest and borrowing costs recognized in profit or loss.', 'Expenses > Finance costs', 'std_other_expense_interest', 'Finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT')
    ) AS v(acc_no, account_name, account_classification, account_head, account_sub, description, international_standard_group, standard_account_code, ifrs_taxonomy_reference, ifrs_source, normal_balance)
    ON CONFLICT (client_id, acc_no) DO UPDATE SET
        account_name = EXCLUDED.account_name,
        account_classification = EXCLUDED.account_classification,
        account_head = EXCLUDED.account_head,
        account_sub = EXCLUDED.account_sub,
        description = EXCLUDED.description,
        international_standard_group = EXCLUDED.international_standard_group,
        standard_account_code = EXCLUDED.standard_account_code,
        ifrs_taxonomy_reference = EXCLUDED.ifrs_taxonomy_reference,
        ifrs_source = EXCLUDED.ifrs_source,
        normal_balance = EXCLUDED.normal_balance,
        client_code = EXCLUDED.client_code,
        edited_at = now();
END
$do$;

-- Verifikasi setelah dijalankan:
-- SELECT m.nama_client, count(*) FROM management_client_coa c
-- JOIN management_clients m ON m.id = c.client_id
-- WHERE c.deleted_at IS NULL GROUP BY m.nama_client;
