-- seed_coa_sau.sql
-- =============================================================
-- Master COA klien SAU -> tabel management_client_coa (95 akun).
-- DIHASILKAN OTOMATIS oleh migrations/generate_seed_coa.py dari
-- dataset/COA/COA_Clients_GOUF.xlsx sheet "COA SAU" -- JANGAN diedit
-- manual, ubah Excel-nya lalu generate ulang.
--
-- normal_balance diturunkan dari ACCOUNT CLASSIFICATION (+ akun kontra),
-- lihat generate_seed_coa.py::normal_balance().
--
-- KLIEN: dicari lewat nama_client IN ('SAU', 'CV SUMBER ALODIE UTAMA'), GAGAL dengan pesan
-- jelas kalau belum ada. client_id/client_code TIDAK di-hardcode.
--
-- PRASYARAT: venv\Scripts\python migrations\16-create_management_client_coa.py
--
-- Cara pakai:
--   cd backend
--   venv\Scripts\python migrations\run_seed.py seed_coa_sau.sql
--
-- Idempotensi: ON CONFLICT (client_id, acc_no) DO UPDATE -- aman dijalankan
-- ulang; isi akun ditimpa dari Excel, akun yang di-soft-delete tetap terhapus.

DO $do$
DECLARE
    v_client_id   UUID;
    v_client_code VARCHAR(50);
BEGIN
    SELECT id, client_code INTO v_client_id, v_client_code
    FROM management_clients
    WHERE deleted_at IS NULL
      AND upper(trim(nama_client)) IN ('SAU', 'CV SUMBER ALODIE UTAMA')
    ORDER BY created_at
    LIMIT 1;

    IF v_client_id IS NULL THEN
        RAISE EXCEPTION 'Klien SAU belum ada di management_clients (dicari nama_client IN (''SAU'', ''CV SUMBER ALODIE UTAMA'')). Buat dulu lewat halaman Clients, lalu jalankan ulang seed ini.';
    END IF;

    INSERT INTO management_client_coa (
        client_id, client_code, acc_no, account_name, account_classification, account_head, account_sub, description, international_standard_group, standard_account_code, ifrs_taxonomy_reference, ifrs_source, normal_balance
    )
    SELECT v_client_id, v_client_code, v.*
    FROM (VALUES
        ('11100001', 'PETTY CASH ACCT', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Petty cash and cash on hand used for daily operational transactions.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_petty', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11100002', 'KAS KASIR', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11100998', 'AYAT SILANG', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash or bank funds in transit or temporary clearing pending settlement.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_transit', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11100999', 'CASH PAYMENT CLEARANCE', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash or bank funds in transit or temporary clearing pending settlement.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_transit', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11200001', 'BANK BCA', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11200002', 'BANK MANDIRI', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11200003', 'BANK BRI', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300001', 'CREDIT CARD', 'ASSET', 'CURRENT ASSET', 'OTHER CURRENT ASSETS', 'Other current assets not separately classified.', 'Assets > Current assets > Other current assets', 'std_asset_current_other', 'Other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300002', 'PIUTANG KARYAWAN', 'ASSET', 'CURRENT ASSET', 'OTHER RECEIVABLES', 'Amounts receivable from employees, including employee advances or loans.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_employee', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300003', 'PIUTANG USAHA', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300004', 'PIUTANG PEMEGANG SAHAM', 'ASSET', 'CURRENT ASSET', 'RELATED PARTY RECEIVABLES', 'Amounts receivable from shareholders, directors, affiliates, or other related parties.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_related_party', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300995', 'PPH PASAL 23', 'ASSET', 'CURRENT ASSET', 'INCOME TAX RECEIVABLE', 'Prepaid or recoverable income taxes, including tax installments and withholding credits.', 'Assets > Current assets > Current tax assets', 'std_asset_current_tax_income_receivable', 'Current tax assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300996', 'PPH PASAL 25', 'ASSET', 'CURRENT ASSET', 'INCOME TAX RECEIVABLE', 'Prepaid or recoverable income taxes, including tax installments and withholding credits.', 'Assets > Current assets > Current tax assets', 'std_asset_current_tax_income_receivable', 'Current tax assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300997', 'PAJAK MASUKAN BELUM DIKREDITKAN', 'ASSET', 'CURRENT ASSET', 'INDIRECT TAX RECEIVABLE', 'Recoverable input VAT or other indirect tax receivable.', 'Assets > Current assets > Current tax and other receivables', 'std_asset_current_tax_vat_receivable', 'Current tax assets / other receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300998', 'PAJAK MASUKAN', 'ASSET', 'CURRENT ASSET', 'INDIRECT TAX RECEIVABLE', 'Recoverable input VAT or other indirect tax receivable.', 'Assets > Current assets > Current tax and other receivables', 'std_asset_current_tax_vat_receivable', 'Current tax assets / other receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300999', 'AR PAYMENT CLEARANCE', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11300100', 'AR OTHER', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11500001', 'PERSEDIAAN CRS', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11500002', 'PERSEDIAAN NGY', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11500003', 'PERSEDIAAN OL', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11500004', 'PERSEDIAAN PCL', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('11500099', 'PERSEDIAAN', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('12100001', 'BANGUNAN', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Buildings and building improvements used in operations.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_building', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('12100999', 'AKUMULASI PENYUSUTAN BANGUNAN', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('12200001', 'F.ASSET I - KOMPUTER', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('12200002', 'F.ASSET I - PERALATAN KANTOR', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('12200999', 'AKUMULASI PENYUSUTAN FIXED ASSET I', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('12300001', 'F.ASSET II - KENDARAAN', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Vehicles used in operations.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_vehicle', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('12300999', 'AKUMULASI PENYUSUTAN FIXED ASSET II', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('12500001', 'SEWA DIBAYAR DIMUKA', 'ASSET', 'CURRENT ASSET', 'PREPAYMENTS', 'Costs paid in advance and recognized as assets until consumed.', 'Assets > Current assets > Prepayments and other current assets', 'std_asset_current_prepayment', 'Prepayments and other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('21200001', 'HUTANG USAHA', 'LIABILITY', 'CURRENT LIABILITY', 'TRADE PAYABLES', 'Amounts payable to suppliers for goods and services received in the ordinary course of business.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_trade', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21200002', 'HUTANG KEPADA PEMEGANG SAHAM', 'LIABILITY', 'NON-CURRENT LIABILITY', 'RELATED PARTY BORROWINGS', 'Borrowings from shareholders or related parties, generally non-current unless contractually due within twelve months.', 'Liabilities > Non-current liabilities > Borrowings / related-party liabilities', 'std_liability_noncurrent_borrowing_related_party', 'Non-current borrowings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21200003', 'AP PAYMENT CLEARANCE', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER CURRENT LIABILITIES', 'Other current liabilities not separately classified.', 'Liabilities > Current liabilities > Other current liabilities', 'std_liability_current_other', 'Other current liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21200004', 'HUTANG BIAYA', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Expenses incurred but not yet invoiced or paid.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_expense', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21200999', 'HUTANG LAINNYA', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER PAYABLES', 'Other short-term payables and unsettled liabilities.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_other', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21300001', 'BIAYA YMH DIBAYAR GAJI', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Accrued payroll, salaries, bonuses, social security, and employee-related expenses.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_employee', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21300002', 'BIAYA YMH DIBAYAR JAMSOSTEK', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Expenses incurred but not yet invoiced or paid.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_expense', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21300999', 'BIAYA YMH DIBAYAR LAINNYA', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Expenses incurred but not yet invoiced or paid.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_expense', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21400001', 'HUTANG PAJAK 4(2) / PP 23', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21400002', 'HUTANG PAJAK 21', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21400003', 'HUTANG PAJAK 23', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21400004', 'HUTANG PAJAK 25/29', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21400005', 'HUTANG PAJAK PPN', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Output VAT or other indirect taxes payable.', 'Liabilities > Current liabilities > Tax liabilities', 'std_liability_current_tax_vat_payable', 'Current tax liabilities / other payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21400006', 'PAJAK KELUARAN', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Output VAT or other indirect taxes payable.', 'Liabilities > Current liabilities > Tax liabilities', 'std_liability_current_tax_vat_payable', 'Current tax liabilities / other payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('21400999', 'HUTANG PAJAK LAINNYA', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('22100001', 'HUTANG BANK', 'LIABILITY', 'CURRENT LIABILITY', 'BORROWINGS', 'Short-term loans, overdrafts, and current portions of borrowings.', 'Liabilities > Current liabilities > Borrowings', 'std_liability_current_borrowing', 'Current borrowings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('31110001', 'MODAL DISETOR - FERRY', 'EQUITY', 'EQUITY', 'OTHER EQUITY', 'Other equity balances not separately classified.', 'Equity > Other equity', 'std_equity_other', 'Other equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('31110002', 'MODAL DISETOR - SURYA', 'EQUITY', 'EQUITY', 'OTHER EQUITY', 'Other equity balances not separately classified.', 'Equity > Other equity', 'std_equity_other', 'Other equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('31110021', 'DIVIDEN', 'EQUITY', 'EQUITY', 'OTHER EQUITY', 'Other equity balances not separately classified.', 'Equity > Other equity', 'std_equity_other', 'Other equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('32100001', 'LABA DITAHAN', 'EQUITY', 'EQUITY', 'RETAINED EARNINGS', 'Accumulated retained earnings or accumulated losses from prior periods.', 'Equity > Retained earnings', 'std_equity_retained_earnings', 'Retained earnings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('32200099', 'LABA TAHUN BERJALAN', 'EQUITY', 'EQUITY', 'CURRENT PERIOD EARNINGS', 'Current period profit or loss carried within equity before closing.', 'Equity > Retained earnings / current period result', 'std_equity_current_period_earnings', 'Retained earnings / profit or loss', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('41110001', 'PENJUALAN CRS', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('41110002', 'PENJUALAN NGY', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('41110003', 'PENJUALAN OL', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('41110004', 'PENJUALAN PCL', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('41110098', 'PENJUALAN', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('41110099', 'DISKON PENJUALAN', 'REVENUE', 'OPERATING REVENUE', 'SALES DEDUCTIONS', 'Sales discounts or rebates presented as a reduction of revenue.', 'Income > Revenue deductions', 'std_revenue_operating_discount', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('41110100', 'RETUR PENJUALAN', 'REVENUE', 'OPERATING REVENUE', 'SALES DEDUCTIONS', 'Sales returns and allowances presented as a reduction of revenue.', 'Income > Revenue deductions', 'std_revenue_operating_return', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('51020001', 'HPP CRS', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('51020002', 'HPP NGY', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('51020003', 'HPP OL', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('51020004', 'HPP PCL', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('51020099', 'HARGA POKOK PENJUALAN', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('51020100', 'DISKON PEMBELIAN', 'COST OF SALES', 'COST OF REVENUE', 'PURCHASE DISCOUNT', 'Purchase discounts reducing cost of sales or inventory cost, depending on accounting policy.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_purchase_discount', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('52010001', 'BIAYA GAJI', 'EXPENSE', 'OPERATING EXPENSE', 'SALARIES & WAGES', 'Salaries, wages, payroll, and regular employee compensation.', 'Expenses > Employee benefits expense', 'std_expense_operating_salary_wages', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010002', 'BIAYA GAJI PEMEGANG SAHAM', 'EXPENSE', 'OPERATING EXPENSE', 'SALARIES & WAGES', 'Salaries, wages, payroll, and regular employee compensation.', 'Expenses > Employee benefits expense', 'std_expense_operating_salary_wages', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010003', 'BIAYA JAMSOSTEK', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010004', 'BIAYA MAKAN BERSAMA', 'EXPENSE', 'OPERATING EXPENSE', 'MEALS & ENTERTAINMENT', 'Meals, entertainment, hospitality, and employee refreshments.', 'Expenses > Operating expenses', 'std_expense_operating_meals_entertainment', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010005', 'BIAYA LEMBUR', 'EXPENSE', 'OPERATING EXPENSE', 'BONUS & OVERTIME', 'Bonuses, overtime, incentives, and holiday allowances.', 'Expenses > Employee benefits expense', 'std_expense_operating_bonus_overtime', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010006', 'BIAYA BONUS/THR', 'EXPENSE', 'OPERATING EXPENSE', 'BONUS & OVERTIME', 'Bonuses, overtime, incentives, and holiday allowances.', 'Expenses > Employee benefits expense', 'std_expense_operating_bonus_overtime', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010007', 'BIAYA ATK', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010008', 'BIAYA PEMELIHARAAN', 'EXPENSE', 'OPERATING EXPENSE', 'REPAIR & MAINTENANCE', 'Repair, maintenance, and upkeep of buildings, vehicles, equipment, and facilities.', 'Expenses > Operating expenses', 'std_expense_operating_repair_maintenance', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010009', 'BIAYA JASA PROFESIONAL', 'EXPENSE', 'OPERATING EXPENSE', 'PROFESSIONAL FEES', 'Legal, audit, accounting, consulting, and other professional service fees.', 'Expenses > Operating expenses', 'std_expense_operating_professional_fees', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010010', 'BIAYA SEWA', 'EXPENSE', 'OPERATING EXPENSE', 'RENT EXPENSE', 'Rent and operating lease expenses not capitalized under applicable accounting requirements.', 'Expenses > Operating expenses', 'std_expense_operating_rent', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010011', 'BIAYA PERLENGKAPAN', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010012', 'BIAYA LISTRIK, AIR, TELEPON', 'EXPENSE', 'OPERATING EXPENSE', 'UTILITIES', 'Electricity, water, gas, power, and other utility costs.', 'Expenses > Operating expenses', 'std_expense_operating_utilities', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010013', 'BIAYA BBM', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010014', 'BIAYA PROMOSI', 'EXPENSE', 'OPERATING EXPENSE', 'MARKETING & PROMOTION', 'Advertising, promotion, marketing, sales commission, and partnership costs.', 'Expenses > Operating expenses', 'std_expense_operating_marketing', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010015', 'BIAYA DEPRESIASI', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010016', 'BIAYA ASURANSI', 'EXPENSE', 'OPERATING EXPENSE', 'INSURANCE', 'Insurance premiums and related insurance expense.', 'Expenses > Operating expenses', 'std_expense_operating_insurance', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010017', 'BIAYA TRANSPORTASI', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010018', 'BIAYA INSTALLMENT', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010019', 'BIAYA RETRIBUSI', 'EXPENSE', 'OPERATING EXPENSE', 'TAXES & LICENSES', 'Non-income taxes, licenses, permits, and levies expensed in operations.', 'Expenses > Operating expenses', 'std_expense_operating_tax_license', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010020', 'BIAYA OPERASIONAL', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010021', 'BIAYA KESEHATAN', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52010099', 'BIAYA LAINNYA', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52110001', 'BIAYA ADM BANK', 'EXPENSE', 'OPERATING EXPENSE', 'BANK & PAYMENT CHARGES', 'Bank administration, merchant discount rate, card charges, transfer charges, and payment processing fees.', 'Expenses > Operating expenses / finance costs', 'std_expense_operating_bank_payment_charges', 'Other operating expenses / finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('52110002', 'BIAYA BUNGA', 'OTHER EXPENSE', 'FINANCE COST', 'INTEREST EXPENSE', 'Interest and borrowing costs recognized in profit or loss.', 'Expenses > Finance costs', 'std_other_expense_interest', 'Finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('70000005', 'BIAYA PAJAK', 'EXPENSE', 'OPERATING EXPENSE', 'TAXES & LICENSES', 'Non-income taxes, licenses, permits, and levies expensed in operations.', 'Expenses > Operating expenses', 'std_expense_operating_tax_license', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('70000006', 'BIAYA PAJAK ATAS BUNGA', 'INCOME TAX', 'INCOME TAX EXPENSE', 'INCOME TAX EXPENSE', 'Current and deferred income tax expense recognized in profit or loss.', 'Expenses > Income tax expense', 'std_income_tax_expense', 'Income tax expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('70000020', 'BIAYA PAJAK PENGHASILAN BADAN', 'INCOME TAX', 'INCOME TAX EXPENSE', 'INCOME TAX EXPENSE', 'Current and deferred income tax expense recognized in profit or loss.', 'Expenses > Income tax expense', 'std_income_tax_expense', 'Income tax expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('70000007', 'PENDAPATAN BUNGA', 'OTHER INCOME', 'NON-OPERATING INCOME', 'INTEREST INCOME', 'Interest income from bank balances, deposits, and other financial assets.', 'Income > Finance income / other income', 'std_other_income_interest', 'Finance income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('70000008', 'PENDAPATAN LAINNYA', 'OTHER INCOME', 'NON-OPERATING INCOME', 'OTHER INCOME', 'Other income not arising from principal operating activities.', 'Income > Other income', 'std_other_income_misc', 'Other income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('70000098', 'LABA/ (RUGI) KURS', 'OTHER INCOME', 'NON-OPERATING INCOME', 'OTHER INCOME', 'Other income not arising from principal operating activities.', 'Income > Other income', 'std_other_income_misc', 'Other income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('70000099', 'LABA/ (RUGI)', 'OTHER INCOME', 'NON-OPERATING INCOME', 'OTHER INCOME', 'Other income not arising from principal operating activities.', 'Income > Other income', 'std_other_income_misc', 'Other income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT')
    ) AS v(acc_no, account_name, account_classification, account_head, account_sub, description, international_standard_group, standard_account_code, ifrs_taxonomy_reference, ifrs_source, normal_balance)
    ON CONFLICT (client_id, acc_no) DO UPDATE SET
        account_name = EXCLUDED.account_name,
        account_classification = EXCLUDED.account_classification,
        account_head = EXCLUDED.account_head,
        account_sub = EXCLUDED.account_sub,
        description = EXCLUDED.description,
        international_standard_group = EXCLUDED.international_standard_group,
        standard_account_code = EXCLUDED.standard_account_code,
        ifrs_taxonomy_reference = EXCLUDED.ifrs_taxonomy_reference,
        ifrs_source = EXCLUDED.ifrs_source,
        normal_balance = EXCLUDED.normal_balance,
        client_code = EXCLUDED.client_code,
        edited_at = now();
END
$do$;

-- Verifikasi setelah dijalankan:
-- SELECT m.nama_client, count(*) FROM management_client_coa c
-- JOIN management_clients m ON m.id = c.client_id
-- WHERE c.deleted_at IS NULL GROUP BY m.nama_client;
