-- seed_coa_nbm.sql
-- =============================================================
-- Master COA klien NBM -> tabel management_client_coa (176 akun).
-- DIHASILKAN OTOMATIS oleh migrations/generate_seed_coa.py dari
-- dataset/COA/COA_Clients_GOUF.xlsx sheet "COA NBM" -- JANGAN diedit
-- manual, ubah Excel-nya lalu generate ulang.
--
-- normal_balance diturunkan dari ACCOUNT CLASSIFICATION (+ akun kontra),
-- lihat generate_seed_coa.py::normal_balance().
--
-- KLIEN: dicari lewat nama_client IN ('NBM', 'PT NAWASANGA BERTATAP MUKA'), GAGAL dengan pesan
-- jelas kalau belum ada. client_id/client_code TIDAK di-hardcode.
--
-- PRASYARAT: venv\Scripts\python migrations\16-create_management_client_coa.py
--
-- Cara pakai:
--   cd backend
--   venv\Scripts\python migrations\run_seed.py seed_coa_nbm.sql
--
-- Idempotensi: ON CONFLICT (client_id, acc_no) DO UPDATE -- aman dijalankan
-- ulang; isi akun ditimpa dari Excel, akun yang di-soft-delete tetap terhapus.

DO $do$
DECLARE
    v_client_id   UUID;
    v_client_code VARCHAR(50);
BEGIN
    SELECT id, client_code INTO v_client_id, v_client_code
    FROM management_clients
    WHERE deleted_at IS NULL
      AND upper(trim(nama_client)) IN ('NBM', 'PT NAWASANGA BERTATAP MUKA')
    ORDER BY created_at
    LIMIT 1;

    IF v_client_id IS NULL THEN
        RAISE EXCEPTION 'Klien NBM belum ada di management_clients (dicari nama_client IN (''NBM'', ''PT NAWASANGA BERTATAP MUKA'')). Buat dulu lewat halaman Clients, lalu jalankan ulang seed ini.';
    END IF;

    INSERT INTO management_client_coa (
        client_id, client_code, acc_no, account_name, account_classification, account_head, account_sub, description, international_standard_group, standard_account_code, ifrs_taxonomy_reference, ifrs_source, normal_balance
    )
    SELECT v_client_id, v_client_code, v.*
    FROM (VALUES
        ('1-10001', 'Kas', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10002', 'Setoran Dalam Perjalanan', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash or bank funds in transit or temporary clearing pending settlement.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_transit', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10003', 'Kas di Mesin Kasir', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10004', 'Kas Kecil', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Petty cash and cash on hand used for daily operational transactions.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_petty', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10005', 'Kas Besar', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10006', 'BCA # 5325107836', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10007', 'BCA # 1350838208', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10008', 'BRI # 059001001642303', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10009', 'KAS Fas a Fas To Go', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10010', 'Kas Mesin Kasir Fas To Go', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash on hand and cash held at operational cash points, excluding bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_on_hand', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10011', 'BRI # 059001001757302', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10999', 'Mekari Pay Escrow Account', 'ASSET', 'CURRENT ASSET', 'CASH & CASH EQUIVALENTS', 'Cash held in bank accounts, including foreign-currency bank balances.', 'Assets > Current assets > Cash and cash equivalents', 'std_asset_current_cash_bank', 'Cash and cash equivalents', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10100', 'Piutang Usaha', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10101', 'Bank Transfer', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10102', 'EDC BCA', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10103', 'EDC BRI', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10104', 'GoFood', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10105', 'GrabFood', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10106', 'Voucher', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10107', 'EDC BRI Fas a Fas To Go', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10108', 'EDC BCA Fas a Fas To Go', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10110', 'Brandpay', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10151', 'Piutang Belum Ditagih', 'ASSET', 'CURRENT ASSET', 'TRADE RECEIVABLES', 'Amounts receivable from customers arising from ordinary operating activities.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_trade', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10152', 'Cadangan Kerugian Piutang', 'ASSET', 'CURRENT ASSET', 'ALLOWANCE FOR CREDIT LOSSES', 'Contra-asset allowance for expected credit losses or doubtful receivables.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_allowance', 'Loss allowance on receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10200', 'Persediaan Barang Makanan', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10201', 'Persediaan Barang Minuman', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10202', 'Persediaan - Kemasan dan Perlengkapan', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10203', 'Persediaan Barang Dalam Proses', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10204', 'Persediaan Barang Jadi', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10205', 'Persediaan Bahan Baku Hampers', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10206', 'Persediaan Hampers Jadi', 'ASSET', 'CURRENT ASSET', 'INVENTORIES', 'Inventories, supplies, raw materials, or goods held for sale or consumption.', 'Assets > Current assets > Inventories', 'std_asset_current_inventory', 'Inventories', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10300', 'Piutang Lainnya', 'ASSET', 'CURRENT ASSET', 'OTHER RECEIVABLES', 'Other current receivables not classified as trade receivables.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_other', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10301', 'Piutang Karyawan', 'ASSET', 'CURRENT ASSET', 'OTHER RECEIVABLES', 'Amounts receivable from employees, including employee advances or loans.', 'Assets > Current assets > Trade and other receivables', 'std_asset_current_receivable_employee', 'Trade and other current receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10401', 'Aset Lancar Lainnya', 'ASSET', 'CURRENT ASSET', 'OTHER CURRENT ASSETS', 'Other current assets not separately classified.', 'Assets > Current assets > Other current assets', 'std_asset_current_other', 'Other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10402', 'Biaya Dibayar Di Muka', 'ASSET', 'CURRENT ASSET', 'PREPAYMENTS', 'Costs paid in advance and recognized as assets until consumed.', 'Assets > Current assets > Prepayments and other current assets', 'std_asset_current_prepayment', 'Prepayments and other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10404', 'Sewa Dibayar dimuka', 'ASSET', 'CURRENT ASSET', 'PREPAYMENTS', 'Costs paid in advance and recognized as assets until consumed.', 'Assets > Current assets > Prepayments and other current assets', 'std_asset_current_prepayment', 'Prepayments and other current assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10500', 'PPN Masukan', 'ASSET', 'CURRENT ASSET', 'INDIRECT TAX RECEIVABLE', 'Recoverable input VAT or other indirect tax receivable.', 'Assets > Current assets > Current tax and other receivables', 'std_asset_current_tax_vat_receivable', 'Current tax assets / other receivables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10501', 'Pajak Dibayar Di Muka - PPh 22', 'ASSET', 'CURRENT ASSET', 'INCOME TAX RECEIVABLE', 'Prepaid or recoverable income taxes, including tax installments and withholding credits.', 'Assets > Current assets > Current tax assets', 'std_asset_current_tax_income_receivable', 'Current tax assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10502', 'Pajak Dibayar Di Muka - PPh 23', 'ASSET', 'CURRENT ASSET', 'INCOME TAX RECEIVABLE', 'Prepaid or recoverable income taxes, including tax installments and withholding credits.', 'Assets > Current assets > Current tax assets', 'std_asset_current_tax_income_receivable', 'Current tax assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10503', 'Pajak Dibayar Di Muka - PPh 25', 'ASSET', 'CURRENT ASSET', 'INCOME TAX RECEIVABLE', 'Prepaid or recoverable income taxes, including tax installments and withholding credits.', 'Assets > Current assets > Current tax assets', 'std_asset_current_tax_income_receivable', 'Current tax assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10700', 'Aset Tetap - Tanah', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Land held for operational use.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_land', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10701', 'Aset Tetap - Bangunan', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Buildings and building improvements used in operations.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_building', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10702', 'Aset Tetap - Building Improvements', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Buildings and building improvements used in operations.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_building', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10703', 'Aset Tetap - Kendaraan', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Vehicles used in operations.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_vehicle', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10704', 'Aset Tetap - Mesin & Peralatan', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10705', 'Aset Tetap - Peralatan dan Perlengkapan Kantor', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10707', 'Peralatan dan perlengkapan Kitchen', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10708', 'Furniture dan Fixtures', 'ASSET', 'NON-CURRENT ASSET', 'PROPERTY, PLANT & EQUIPMENT', 'Machinery, office equipment, kitchen equipment, furniture, fixtures, and other operational equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_equipment', 'Property, plant and equipment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('1-10751', 'Akumulasi Penyusutan - Bangunan', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10752', 'Akumulasi Penyusutan - Building Improvements', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10753', 'Akumulasi penyusutan - Kendaraan', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10754', 'Akumulasi Penyusutan - Mesin & Peralatan', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10755', 'Akumulasi Penyusutan - Peralatan dan Perlengkapan Kantor', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10756', 'Akumulasi Penyusutan - Aset Sewa Guna Usaha', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10757', 'Akumulasi Penyusutan Furniture Fixtures', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10758', 'Akumulasi Penyusutan Peralatan  dan Perlengkapan Kitchen', 'ASSET', 'NON-CURRENT ASSET', 'ACCUMULATED DEPRECIATION', 'Contra-asset accumulated depreciation related to property, plant and equipment.', 'Assets > Non-current assets > Property, plant and equipment', 'std_asset_noncurrent_ppe_accum_depreciation', 'Accumulated depreciation and impairment', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('1-10800', 'Investasi', 'ASSET', 'NON-CURRENT ASSET', 'INVESTMENTS', 'Long-term investments and financial placements not classified as cash equivalents.', 'Assets > Non-current assets > Financial assets / investments', 'std_asset_noncurrent_investment', 'Other non-current financial assets', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('2-20100', 'Hutang Usaha', 'LIABILITY', 'CURRENT LIABILITY', 'TRADE PAYABLES', 'Amounts payable to suppliers for goods and services received in the ordinary course of business.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_trade', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20150', 'Hutang Belum Ditagih', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER PAYABLES', 'Other short-term payables and unsettled liabilities.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_other', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20200', 'Hutang Lain Lain', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER PAYABLES', 'Other short-term payables and unsettled liabilities.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_other', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20201', 'Hutang Gaji', 'LIABILITY', 'CURRENT LIABILITY', 'ACCRUED EXPENSES', 'Accrued payroll, salaries, bonuses, social security, and employee-related expenses.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_accrued_employee', 'Accruals and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20202', 'Hutang Deviden', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER PAYABLES', 'Other short-term payables and unsettled liabilities.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_other', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20203', 'Pendapatan Diterima Di Muka', 'LIABILITY', 'CURRENT LIABILITY', 'CONTRACT / DEFERRED REVENUE', 'Customer deposits, advances, or revenue received before the related performance obligation is satisfied.', 'Liabilities > Current liabilities > Contract liabilities and other payables', 'std_liability_current_deferred_revenue', 'Contract liabilities / other current liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20401', 'Hutang Service Charge', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER PAYABLES', 'Other short-term payables and unsettled liabilities.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_other', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20402', 'Hutang PB1', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Other taxes and local levies payable, including sales/service taxes where applicable.', 'Liabilities > Current liabilities > Tax liabilities', 'std_liability_current_tax_other_payable', 'Current tax liabilities / other payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20403', 'Hutang Konsinyasi', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER PAYABLES', 'Other short-term payables and unsettled liabilities.', 'Liabilities > Current liabilities > Trade and other payables', 'std_liability_current_payable_other', 'Trade and other current payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20500', 'PPN Keluaran', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Output VAT or other indirect taxes payable.', 'Liabilities > Current liabilities > Tax liabilities', 'std_liability_current_tax_vat_payable', 'Current tax liabilities / other payables', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20501', 'Hutang Pajak - PPh 21', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20502', 'Hutang Pajak - PPh 22', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20503', 'Hutang Pajak - PPh 23', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20504', 'Hutang Pajak - PPh 29', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20599', 'Hutang Pajak Lainnya', 'LIABILITY', 'CURRENT LIABILITY', 'TAX PAYABLES', 'Income tax withholding, installments, or corporate income tax payable.', 'Liabilities > Current liabilities > Current tax liabilities', 'std_liability_current_tax_income_payable', 'Current tax liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20601', 'Kewajiban Lancar Lainnya', 'LIABILITY', 'CURRENT LIABILITY', 'OTHER CURRENT LIABILITIES', 'Other current liabilities not separately classified.', 'Liabilities > Current liabilities > Other current liabilities', 'std_liability_current_other', 'Other current liabilities', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20700', 'Kewajiban Manfaat Karyawan', 'LIABILITY', 'NON-CURRENT LIABILITY', 'EMPLOYEE BENEFIT OBLIGATIONS', 'Long-term employee benefit or post-employment benefit obligations.', 'Liabilities > Non-current liabilities > Employee benefit obligations', 'std_liability_noncurrent_employee_benefit', 'Employee benefit obligations', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('2-20701', 'Hutang kepada Pemegang Saham', 'LIABILITY', 'NON-CURRENT LIABILITY', 'RELATED PARTY BORROWINGS', 'Borrowings from shareholders or related parties, generally non-current unless contractually due within twelve months.', 'Liabilities > Non-current liabilities > Borrowings / related-party liabilities', 'std_liability_noncurrent_borrowing_related_party', 'Non-current borrowings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-30000', 'Modal Saham', 'EQUITY', 'EQUITY', 'SHARE CAPITAL', 'Issued and paid-in share capital or owners'' capital.', 'Equity > Share capital', 'std_equity_share_capital', 'Issued capital', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-30001', 'Tambahan Modal Disetor', 'EQUITY', 'EQUITY', 'ADDITIONAL PAID-IN CAPITAL', 'Additional paid-in capital, share premium, or similar contributed equity.', 'Equity > Other contributed equity', 'std_equity_additional_paid_in_capital', 'Share premium / other contributed equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-30100', 'Laba Ditahan', 'EQUITY', 'EQUITY', 'RETAINED EARNINGS', 'Accumulated retained earnings or accumulated losses from prior periods.', 'Equity > Retained earnings', 'std_equity_retained_earnings', 'Retained earnings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-30200', 'Deviden', 'EQUITY', 'EQUITY', 'OWNER DRAWINGS', 'Owner drawings or distributions recorded directly in equity.', 'Equity > Other equity', 'std_equity_owner_drawing', 'Other equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('3-30300', 'Pendapatan Komprehensif Lainnya', 'EQUITY', 'EQUITY', 'OTHER COMPREHENSIVE INCOME', 'Accumulated or current other comprehensive income items recognized in equity.', 'Equity > Other reserves / OCI', 'std_equity_oci', 'Other comprehensive income / reserves', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-30999', 'Ekuitas Saldo Awal', 'EQUITY', 'EQUITY', 'OTHER EQUITY', 'Other equity balances not separately classified.', 'Equity > Other equity', 'std_equity_other', 'Other equity', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-30003', 'Retained Earnings', 'EQUITY', 'EQUITY', 'RETAINED EARNINGS', 'Accumulated retained earnings or accumulated losses from prior periods.', 'Equity > Retained earnings', 'std_equity_retained_earnings', 'Retained earnings', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('3-30002', 'Current Period Earnings', 'EQUITY', 'EQUITY', 'CURRENT PERIOD EARNINGS', 'Current period profit or loss carried within equity before closing.', 'Equity > Retained earnings / current period result', 'std_equity_current_period_earnings', 'Retained earnings / profit or loss', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-40000', 'Sales Retail', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-40001', 'Pendapatan Minuman', 'REVENUE', 'OPERATING REVENUE', 'FOOD & BEVERAGE REVENUE', 'Restaurant, café, food, and beverage revenue.', 'Income > Revenue', 'std_revenue_operating_food_beverage', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-40002', 'Pendapatan Katering', 'REVENUE', 'OPERATING REVENUE', 'EVENT / CATERING REVENUE', 'Revenue from events, catering, or similar activity-specific services.', 'Income > Revenue', 'std_revenue_operating_event_catering', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-40003', 'Pendapatan Wholesale', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-40004', 'Pendapatan Event', 'REVENUE', 'OPERATING REVENUE', 'EVENT / CATERING REVENUE', 'Revenue from events, catering, or similar activity-specific services.', 'Income > Revenue', 'std_revenue_operating_event_catering', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-40005', 'Pendapatan Fas To Go', 'REVENUE', 'OPERATING REVENUE', 'SALES REVENUE', 'Revenue from sale of goods in the ordinary course of business.', 'Income > Revenue', 'std_revenue_operating_sales', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('7-70005', 'Pendapatan Hampers', 'REVENUE', 'OPERATING REVENUE', 'EVENT / CATERING REVENUE', 'Revenue from events, catering, or similar activity-specific services.', 'Income > Revenue', 'std_revenue_operating_event_catering', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('4-40100', 'Sales Discount', 'REVENUE', 'OPERATING REVENUE', 'SALES DEDUCTIONS', 'Sales discounts or rebates presented as a reduction of revenue.', 'Income > Revenue deductions', 'std_revenue_operating_discount', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('4-40200', 'Sales Return', 'REVENUE', 'OPERATING REVENUE', 'SALES DEDUCTIONS', 'Sales returns and allowances presented as a reduction of revenue.', 'Income > Revenue deductions', 'std_revenue_operating_return', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('4-40201', 'Pendapatan Belum Ditagih', 'REVENUE', 'OPERATING REVENUE', 'UNBILLED REVENUE', 'Revenue recognized before billing to the customer, subject to contract/accounting policy.', 'Income > Revenue', 'std_revenue_operating_unbilled', 'Revenue', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('5-50000', 'Harga Pokok Penjualan (HPP) Makanan', 'COST OF SALES', 'COST OF REVENUE', 'DIRECT MATERIAL / FOOD COST', 'Direct cost of materials, food, ingredients, or goods consumed in producing revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_direct_material', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('5-50001', 'Beban Pokok Pendapatan Minuman', 'COST OF SALES', 'COST OF REVENUE', 'BEVERAGE COST', 'Direct beverage cost associated with revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_beverage', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('5-50002', 'Beban Pokok Pendapatan Waste', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('5-50003', 'Harga Pokok Penjualan Hampers', 'COST OF SALES', 'COST OF REVENUE', 'OTHER COST OF SALES', 'Other direct costs attributable to generating revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_other', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('5-50100', 'Diskon Pembelian', 'COST OF SALES', 'COST OF REVENUE', 'PURCHASE DISCOUNT', 'Purchase discounts reducing cost of sales or inventory cost, depending on accounting policy.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_purchase_discount', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('5-50200', 'Retur Pembelian', 'COST OF SALES', 'COST OF REVENUE', 'PURCHASE RETURN', 'Purchase returns reducing cost of sales or inventory cost, depending on accounting policy.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_purchase_return', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('5-50300', 'Pengiriman & Pengangkutan', 'COST OF SALES', 'COST OF REVENUE', 'FREIGHT / DELIVERY COST', 'Freight, delivery, and handling costs directly attributable to goods or services sold.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_freight', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('5-50500', 'Biaya Produksi', 'COST OF SALES', 'COST OF REVENUE', 'PRODUCTION COST', 'Other direct production or service-delivery costs attributable to revenue.', 'Expenses > Cost of sales / cost of revenue', 'std_cost_of_sales_production', 'Cost of sales', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60000', 'Biaya Penjualan', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60001', 'Iklan & Promosi', 'EXPENSE', 'OPERATING EXPENSE', 'MARKETING & PROMOTION', 'Advertising, promotion, marketing, sales commission, and partnership costs.', 'Expenses > Operating expenses', 'std_expense_operating_marketing', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60003', 'Bensin, Tol dan Parkir - Penjualan', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60004', 'Perjalanan Dinas - Penjualan', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60006', 'Marketing Lainnya', 'EXPENSE', 'OPERATING EXPENSE', 'MARKETING & PROMOTION', 'Advertising, promotion, marketing, sales commission, and partnership costs.', 'Expenses > Operating expenses', 'std_expense_operating_marketing', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60009', 'Marketplace Ads', 'EXPENSE', 'OPERATING EXPENSE', 'MARKETING & PROMOTION', 'Advertising, promotion, marketing, sales commission, and partnership costs.', 'Expenses > Operating expenses', 'std_expense_operating_marketing', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60008', 'Biaya Kemitraan', 'EXPENSE', 'OPERATING EXPENSE', 'MARKETING & PROMOTION', 'Advertising, promotion, marketing, sales commission, and partnership costs.', 'Expenses > Operating expenses', 'std_expense_operating_marketing', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60050', 'Biaya Pra Operasi', 'EXPENSE', 'OPERATING EXPENSE', 'PRE-OPERATING EXPENSE', 'Pre-opening or pre-operational costs expensed as incurred unless capitalization criteria are met.', 'Expenses > Operating expenses', 'std_expense_operating_preoperating', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60100', 'Biaya Umum & Administratif', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60007', 'Seragam Pegawai', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60101', 'Gaji', 'EXPENSE', 'OPERATING EXPENSE', 'SALARIES & WAGES', 'Salaries, wages, payroll, and regular employee compensation.', 'Expenses > Employee benefits expense', 'std_expense_operating_salary_wages', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60102', 'Biaya Penelitian dan Pengembangan', 'EXPENSE', 'OPERATING EXPENSE', 'RESEARCH & DEVELOPMENT', 'Research and development expenditure recognized as expense when capitalization criteria are not met.', 'Expenses > Operating expenses', 'std_expense_operating_research_development', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60103', 'Makanan & Transportasi', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60104', 'Lembur', 'EXPENSE', 'OPERATING EXPENSE', 'BONUS & OVERTIME', 'Bonuses, overtime, incentives, and holiday allowances.', 'Expenses > Employee benefits expense', 'std_expense_operating_bonus_overtime', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60105', 'Pengobatan', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60106', 'THR & Bonus', 'EXPENSE', 'OPERATING EXPENSE', 'BONUS & OVERTIME', 'Bonuses, overtime, incentives, and holiday allowances.', 'Expenses > Employee benefits expense', 'std_expense_operating_bonus_overtime', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60108', 'Insentif', 'EXPENSE', 'OPERATING EXPENSE', 'BONUS & OVERTIME', 'Bonuses, overtime, incentives, and holiday allowances.', 'Expenses > Employee benefits expense', 'std_expense_operating_bonus_overtime', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60109', 'Pesangon', 'EXPENSE', 'OPERATING EXPENSE', 'SEVERANCE / POST-EMPLOYMENT COST', 'Severance and employee benefit expense related to termination or post-employment obligations.', 'Expenses > Employee benefits expense', 'std_expense_operating_severance', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60110', 'Manfaat dan Tunjangan Lain', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60200', 'Donasi', 'EXPENSE', 'OPERATING EXPENSE', 'DONATION & COMMUNITY', 'Donations and community-related expenditure.', 'Expenses > Other operating expenses', 'std_expense_operating_donation', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60201', 'Hiburan', 'EXPENSE', 'OPERATING EXPENSE', 'MEALS & ENTERTAINMENT', 'Meals, entertainment, hospitality, and employee refreshments.', 'Expenses > Operating expenses', 'std_expense_operating_meals_entertainment', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60202', 'Bensin, Tol dan Parkir - Umum', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60203', 'Perbaikan & Pemeliharaan', 'EXPENSE', 'OPERATING EXPENSE', 'REPAIR & MAINTENANCE', 'Repair, maintenance, and upkeep of buildings, vehicles, equipment, and facilities.', 'Expenses > Operating expenses', 'std_expense_operating_repair_maintenance', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60204', 'Perjalanan Dinas - Umum', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60205', 'Makanan', 'EXPENSE', 'OPERATING EXPENSE', 'MEALS & ENTERTAINMENT', 'Meals, entertainment, hospitality, and employee refreshments.', 'Expenses > Operating expenses', 'std_expense_operating_meals_entertainment', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60209', 'Biaya Hukum dan Profesional', 'EXPENSE', 'OPERATING EXPENSE', 'PROFESSIONAL FEES', 'Legal, audit, accounting, consulting, and other professional service fees.', 'Expenses > Operating expenses', 'std_expense_operating_professional_fees', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60210', 'Beban Manfaat Karyawan', 'EXPENSE', 'OPERATING EXPENSE', 'EMPLOYEE BENEFITS', 'Employee benefits, allowances, social security, health, and welfare costs.', 'Expenses > Employee benefits expense', 'std_expense_operating_employee_benefits', 'Employee benefits expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60213', 'Beban Piutang Tak Tertagih', 'EXPENSE', 'OPERATING EXPENSE', 'CREDIT LOSS / BAD DEBT', 'Bad debt or expected credit loss expense on receivables.', 'Expenses > Impairment / credit loss', 'std_expense_operating_credit_loss', 'Impairment loss / credit loss expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60214', 'Pajak dan Perizinan', 'EXPENSE', 'OPERATING EXPENSE', 'TAXES & LICENSES', 'Non-income taxes, licenses, permits, and levies expensed in operations.', 'Expenses > Operating expenses', 'std_expense_operating_tax_license', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60217', 'Biaya Listrik dan Air PAM', 'EXPENSE', 'OPERATING EXPENSE', 'UTILITIES', 'Electricity, water, gas, power, and other utility costs.', 'Expenses > Operating expenses', 'std_expense_operating_utilities', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60219', 'Biaya Internet dan Telepon', 'EXPENSE', 'OPERATING EXPENSE', 'COMMUNICATION & INTERNET', 'Telephone, internet, communication, and connectivity costs.', 'Expenses > Operating expenses', 'std_expense_operating_communication', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60221', 'Langganan Software', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60300', 'Biaya Kantor', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60301', 'Biaya Alat Tulis Kantor dan Percetakan', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60303', 'Keamanan dan Kebersihan', 'EXPENSE', 'OPERATING EXPENSE', 'CLEANING & SECURITY', 'Cleaning, security, waste removal, and related facility-support costs.', 'Expenses > Operating expenses', 'std_expense_operating_cleaning_security', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60304', 'Supplies dan Material', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60400', 'Biaya Sewa - Tanah', 'EXPENSE', 'OPERATING EXPENSE', 'RENT EXPENSE', 'Rent and operating lease expenses not capitalized under applicable accounting requirements.', 'Expenses > Operating expenses', 'std_expense_operating_rent', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60401', 'Biaya Sewa - Kendaraan', 'EXPENSE', 'OPERATING EXPENSE', 'RENT EXPENSE', 'Rent and operating lease expenses not capitalized under applicable accounting requirements.', 'Expenses > Operating expenses', 'std_expense_operating_rent', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60402', 'Biaya Sewa - Operasional', 'EXPENSE', 'OPERATING EXPENSE', 'RENT EXPENSE', 'Rent and operating lease expenses not capitalized under applicable accounting requirements.', 'Expenses > Operating expenses', 'std_expense_operating_rent', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60403', 'Biaya Sewa - Lain - lain', 'EXPENSE', 'OPERATING EXPENSE', 'RENT EXPENSE', 'Rent and operating lease expenses not capitalized under applicable accounting requirements.', 'Expenses > Operating expenses', 'std_expense_operating_rent', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60404', 'Outlet Commission or Manejement Outlet Expense', 'EXPENSE', 'OPERATING EXPENSE', 'MARKETING & PROMOTION', 'Advertising, promotion, marketing, sales commission, and partnership costs.', 'Expenses > Operating expenses', 'std_expense_operating_marketing', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60450', 'MDR EDC BCA', 'EXPENSE', 'OPERATING EXPENSE', 'BANK & PAYMENT CHARGES', 'Bank administration, merchant discount rate, card charges, transfer charges, and payment processing fees.', 'Expenses > Operating expenses / finance costs', 'std_expense_operating_bank_payment_charges', 'Other operating expenses / finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60455', 'MDR EDC BRI', 'EXPENSE', 'OPERATING EXPENSE', 'BANK & PAYMENT CHARGES', 'Bank administration, merchant discount rate, card charges, transfer charges, and payment processing fees.', 'Expenses > Operating expenses / finance costs', 'std_expense_operating_bank_payment_charges', 'Other operating expenses / finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60500', 'Penyusutan - Bangunan', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60501', 'Penyusutan - Perbaikan Bangunan', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60502', 'Penyusutan - Kendaraan', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60503', 'Penyusutan - Mesin & Peralatan', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60504', 'Penyusutan - Peralatan Kantor', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60599', 'Penyusutan - Aset Sewa Guna Usaha', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60202 A', 'Biaya BBM,tol,parkir - Preparations', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60204 A', 'Biaya perjalanan dinas - preparation', 'EXPENSE', 'OPERATING EXPENSE', 'TRANSPORT & TRAVEL', 'Fuel, toll, parking, transportation, vehicle operating costs, and business travel.', 'Expenses > Operating expenses', 'std_expense_operating_transport_travel', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60216', 'Pengeluaran Barang Rusak', 'EXPENSE', 'OPERATING EXPENSE', 'OTHER OPERATING EXPENSE', 'Other operating expense not separately classified.', 'Expenses > Operating expenses', 'std_expense_operating_other', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60222', 'Canang Harian', 'EXPENSE', 'OPERATING EXPENSE', 'DONATION & COMMUNITY', 'Donations and community-related expenditure.', 'Expenses > Other operating expenses', 'std_expense_operating_donation', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60225', 'Biaya Perlengkapan Bar', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60226', 'Biaya Pengemasan', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60227', 'Biaya Perlengkapan Dapur', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60228', 'Biaya Perlengkapan Operasional', 'EXPENSE', 'OPERATING EXPENSE', 'OPERATING SUPPLIES', 'Kitchen, bar, guest, cleaning, packaging, and other consumable operating supplies.', 'Expenses > Operating expenses', 'std_expense_operating_supplies', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60229', 'Biaya Air Minum Karyawan', 'EXPENSE', 'OPERATING EXPENSE', 'OFFICE & ADMINISTRATION', 'Office supplies, stationery, printing, administration, and general office costs.', 'Expenses > Operating expenses', 'std_expense_operating_office_admin', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60310', 'Biaya Renovasi bangunan gedung', 'EXPENSE', 'OPERATING EXPENSE', 'REPAIR & MAINTENANCE', 'Repair, maintenance, and upkeep of buildings, vehicles, equipment, and facilities.', 'Expenses > Operating expenses', 'std_expense_operating_repair_maintenance', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60505', 'Penyusutan Peralatan Kitchen', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('6-60506', 'Penyusutan Furniture dan Fixtures', 'EXPENSE', 'OPERATING EXPENSE', 'DEPRECIATION', 'Depreciation expense for property, plant and equipment.', 'Expenses > Depreciation and amortisation expense', 'std_expense_operating_depreciation', 'Depreciation and amortisation expense', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('7-70000', 'Pendapatan Bunga - Bank', 'OTHER INCOME', 'NON-OPERATING INCOME', 'INTEREST INCOME', 'Interest income from bank balances, deposits, and other financial assets.', 'Income > Finance income / other income', 'std_other_income_interest', 'Finance income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('7-70001', 'Pendapatan Bunga - Deposito', 'OTHER INCOME', 'NON-OPERATING INCOME', 'INTEREST INCOME', 'Interest income from bank balances, deposits, and other financial assets.', 'Income > Finance income / other income', 'std_other_income_interest', 'Finance income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('7-70002', 'Pendapatan Komisi - Barang Konsinyasi', 'OTHER INCOME', 'NON-OPERATING INCOME', 'COMMISSION / OTHER INVESTMENT INCOME', 'Commission or similar income presented outside primary operating revenue based on the source COA presentation.', 'Income > Other income', 'std_other_income_commission', 'Other income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('7-70003', 'Pembulatan', 'OTHER INCOME', 'NON-OPERATING INCOME', 'OTHER INCOME', 'Other income not arising from principal operating activities.', 'Income > Other income', 'std_other_income_misc', 'Other income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('7-70004', 'Rounding', 'OTHER INCOME', 'NON-OPERATING INCOME', 'OTHER INCOME', 'Other income not arising from principal operating activities.', 'Income > Other income', 'std_other_income_misc', 'Other income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('7-70099', 'Pendapatan Lain - lain', 'OTHER INCOME', 'NON-OPERATING INCOME', 'OTHER INCOME', 'Other income not arising from principal operating activities.', 'Income > Other income', 'std_other_income_misc', 'Other income', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'CREDIT'),
        ('8-80000', 'Beban Bunga', 'OTHER EXPENSE', 'FINANCE COST', 'INTEREST EXPENSE', 'Interest and borrowing costs recognized in profit or loss.', 'Expenses > Finance costs', 'std_other_expense_interest', 'Finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-80001', 'Provisi', 'OTHER EXPENSE', 'NON-OPERATING EXPENSE', 'OTHER EXPENSE', 'Other non-operating expense not separately classified.', 'Expenses > Other expenses', 'std_other_expense_misc', 'Other expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-80002', '(Laba)/Rugi Pelepasan Aset Tetap', 'OTHER EXPENSE', 'NON-OPERATING EXPENSE', 'LOSS ON DISPOSAL', 'Loss on disposal or write-off of property, plant and equipment or other assets.', 'Expenses > Other expenses', 'std_other_expense_loss_disposal', 'Other expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-80004', 'Biaya Uji Coba Produk', 'OTHER EXPENSE', 'NON-OPERATING EXPENSE', 'OTHER EXPENSE', 'Other non-operating expense not separately classified.', 'Expenses > Other expenses', 'std_other_expense_misc', 'Other expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-80005', 'Biaya pengiriman barang', 'EXPENSE', 'OPERATING EXPENSE', 'FREIGHT & COURIER', 'Courier, expedition, shipping, and delivery costs not classified as cost of sales.', 'Expenses > Operating expenses', 'std_expense_operating_freight_courier', 'Other operating expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-80006', 'Administrasi Bank', 'EXPENSE', 'OPERATING EXPENSE', 'BANK & PAYMENT CHARGES', 'Bank administration, merchant discount rate, card charges, transfer charges, and payment processing fees.', 'Expenses > Operating expenses / finance costs', 'std_expense_operating_bank_payment_charges', 'Other operating expenses / finance costs', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-80100', 'Penyesuaian Persediaan', 'OTHER EXPENSE', 'NON-OPERATING EXPENSE', 'OTHER EXPENSE', 'Other non-operating expense not separately classified.', 'Expenses > Other expenses', 'std_other_expense_misc', 'Other expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT'),
        ('8-80999', 'Beban Lain - lain', 'OTHER EXPENSE', 'NON-OPERATING EXPENSE', 'OTHER EXPENSE', 'Other non-operating expense not separately classified.', 'Expenses > Other expenses', 'std_other_expense_misc', 'Other expenses', 'https://www.ifrs.org/issued-standards/ifrs-taxonomy/', 'DEBIT')
    ) AS v(acc_no, account_name, account_classification, account_head, account_sub, description, international_standard_group, standard_account_code, ifrs_taxonomy_reference, ifrs_source, normal_balance)
    ON CONFLICT (client_id, acc_no) DO UPDATE SET
        account_name = EXCLUDED.account_name,
        account_classification = EXCLUDED.account_classification,
        account_head = EXCLUDED.account_head,
        account_sub = EXCLUDED.account_sub,
        description = EXCLUDED.description,
        international_standard_group = EXCLUDED.international_standard_group,
        standard_account_code = EXCLUDED.standard_account_code,
        ifrs_taxonomy_reference = EXCLUDED.ifrs_taxonomy_reference,
        ifrs_source = EXCLUDED.ifrs_source,
        normal_balance = EXCLUDED.normal_balance,
        client_code = EXCLUDED.client_code,
        edited_at = now();
END
$do$;

-- Verifikasi setelah dijalankan:
-- SELECT m.nama_client, count(*) FROM management_client_coa c
-- JOIN management_clients m ON m.id = c.client_id
-- WHERE c.deleted_at IS NULL GROUP BY m.nama_client;
